name: Update data.json every 15 minutes

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:  # To umožní ruční spuštění přes GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch API data and update data.json
        run: |
          echo "Spouštím update_data.py"
          python3 scripts/update_data.py

      - name: Commit and push if changes
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if ! git diff --quiet; then
            git add data.json
            git commit -m "Update data.json via GitHub Actions"
            git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          fi
