name: Update data.json every 15 minutes

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch API data and update data.json
        run: |
          curl -s -X GET "https://v3.football.api-sports.io/fixtures?season=2023&next=500" \
            -H "x-apisports-key: 8bb57fb34476880013cbe2f37d283451" \
            -H "accept: application/json" > raw.json
          python3 scripts/update_data.py

      - name: Commit and push if changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if ! git diff --quiet; then
            git add data.json
            git commit -m "Update data.json via GitHub Actions"
            git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          fi
